import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import ffmpeg from "ffmpeg";
import path from "path";
import fs from "fs"


const runFFMPEG = async () => {
  // console.log(path.resolve("videos", "city.mp4"))

  try {
    const process = new ffmpeg(path.resolve("public/videos/mp4", "city.mp4"));
      process.then((video) => {
        console.log("The video is ready to be processed");
      }, (err) => {
        console.log("Error: " + err);
      });
  } catch (error) {
    console.error({ error });
  }
}

const Home: NextPage = ({ data }) => {
  console.log(data)
  // runFFMPEG();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    </div>
  )
}

// Home.getInitialProps = async () => {
//   // const data = fs.readFileSync(path.resolve("public/videos/mp4", "city.mp4"), "utf-8")
//   let test;
//   const process = new ffmpeg(path.resolve("public/videos/mp4", "city.mp4"));
//     process.then((video) => {
//       test = "The video is ready to be processed" 
//     }, (err) => {
//       test = "Error: " + err
//     });

//   return {
//     data: test
//   }
// };

export default Home
